version: '2.2'
services:

  cadvisor:
    image: google/cadvisor:latest
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1

    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

    expose:
      - 5000
    networks:
      - elastic


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - es01
    ports:
      - 4000:4000

volumes:
  data01:
    driver: local


networks:
  elastic:
    driver: bridge
